### ISSUE TITLE
Please also add error handling example

### ISSUE THREAD

**Issue by martinsookael** [ruipgil/scraperjs#24]
Hi! 

Really like your library. 
I cannot figure out how to make it handle errors (wrong URL for example). 
Could you add this somewhere?

Greetings,
Martin

**Comment by ruipgil** [comment]
Hi,
You're completely right, I'll add a couple of examples in the next few days.
Thank you, for your input.

**Comment by chmac** [comment]
Any update on this? Don't see any error handling in the examples...

**Comment by mreid1130** [comment]
would love to see some examples of error handling as well

**Comment by ruipgil** [comment]
I've added [one example](https://github.com/ruipgil/scraperjs/blob/master/doc/examples/ErrorHandling.js) that covers various cases of how to handle errors.

**Comment by chmac** [comment]
@ruipgil Awesome, thanks. Does the same approach of using `throw` work in the DynamicScraper?

**Comment by ruipgil** [comment]
Good point @chmac ! In the dynamic scraper, exceptions from the ``` scrape ``` promise cannot be catch by the ``` onError ``` promise. I may tweak the code to take it into account.
