### ISSUE TITLE
Doesn't install phantomjs dependency, fresh install

### ISSUE THREAD

**Issue by ssteinerx** [ruipgil/scraperjs#30]
Fresh install in new directory with nothing else installed other than this package.

Running the two examples from README.md:

https://gist.github.com/ssteinerx/d0e6619a5a7e6d9223a2

**Comment by ruipgil** [comment]
Yes, it is true.
However, because phantom is a binary, and platform specific, it should be installed by the user.
I'll update the README with the necessary information.
