### ISSUE TITLE
using 32 bit 10.37 node.js -- the test fails

### ISSUE THREAD

**Issue by smartmouse** [ruipgil/scraperjs#31]
First: thank you for writing this npm module , nice work.
on Ubuntu 14.x x-linux
using 64 bits nodej.s -v0.10.37
the tests works great.

  110 passing (15s)

>> =============================================================================
>> Writing coverage object [/home/ivyho2/ivyTest/node_modules/scraperjs/coverage/coverage.json]
>> Writing coverage reports at [/home/ivyho2/ivyTest/node_modules/scraperjs/coverage]
>> =============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 337/337 )
Branches     : 100% ( 111/111 )
Functions    : 98.15% ( 106/108 )
Lines        : 100% ( 337/337 )
================================================================================

Running "exec:check-coverage" (exec) task

Running "unserve" task

Done, without errors.

Using 32 bit node.js v10.37

      usage of utils
        ✓ stop()
        ✓ scraper
        ✓ params
    with DynamicScraper
      with Factory
>>
>> assert.js:93
>>   throw new assert.AssertionError({
>>         ^
>> AssertionError: "abnormal phantomjs exit code: 127" == "random message"
>>     at Domain.<anonymous> (/home/ivyho/testIvy/node_modules/scraperjs/test/ScraperPromise.js:92:12)
>>     at Domain.emit (events.js:95:17)
>>     at process._fatalException (node.js:263:29)
>> Exited with code: 7.
Warning: Task "exec:coverage" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

Is it a phantomjs issue?

**Comment by ruipgil** [comment]
Some dependencies, namely ```request```, were having some issues with v0.12. I'll update it soo.
