### ISSUE TITLE
using 32 bit node.js version 0.12 -- 44 tests failed

### ISSUE THREAD

**Issue by smartmouse** [ruipgil/scraperjs#32]
StaticScraper
    ✓ .clone
    #create
      ✓ with argument
      ✓ without argument
    .loadBody, .scrape, .close
      ✓ without errors
      ✓ with errors

  69 passing (4s)
>>   44 failing
>>   1) DynamicScraper .loadBody, .scrape, .close:
>>      Uncaught AssertionError: abnormal phantomjs exit code: 127
>>       at Console.assert (console.js:106:23)
>>       at ChildProcess.<anonymous> (/home/nodetest/test/node_modules/scraperjs/node_modules/phantom/phantom.js:153:28)

However, using 64 bit node.js version 0.12 -- everything passed
  StaticScraper
    ✓ .clone
    #create
      ✓ with argument
      ✓ without argument
    .loadBody, .scrape, .close
      ✓ without errors
      ✓ with errors

  110 passing (18s)

>> =============================================================================
>> Writing coverage object [/home/nodetest/test/node_modules/scraperjs/coverage/coverage.json]
>> Writing coverage reports at [/home/nodetest/test/node_modules/scraperjs/coverage]
>> =============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 337/337 )
Branches     : 100% ( 111/111 )
Functions    : 98.15% ( 106/108 )
Lines        : 100% ( 337/337 )
================================================================================

Running "exec:check-coverage" (exec) task

Running "unserve" task

Done, without errors.

**Comment by ruipgil** [comment]
Related to #31
