### ISSUE TITLE
Passing options to phantom

### ISSUE THREAD

**Issue by vdraceil** [ruipgil/scraperjs#33]
Is there a way to pass options (like load-images: no, load-styles: no, etc.) to the DynamicScraper?
Its just that some pages may load faster without the resources.

**Comment by ruipgil** [comment]
Currently there's no practical way to do it. However, by default ``` load-images ``` is [set to no](https://github.com/ruipgil/scraperjs/blob/master/src/DynamicScraper.js#L38).
