### ISSUE TITLE
DynamicScraper: Support timeout for page loading

### ISSUE THREAD

**Issue by IvanGoncharov** [ruipgil/scraperjs#35]
During scrapping I encounter couple pages that hangup during loading.
I'm doing scrapping on thousands of pages in parallel, and some of them stuck forever(at least 10+ min).
Timeout will solve this problem, ideally it would have user supplied value, but reasonable hardcode is also good.

**Comment by ruipgil** [comment]
That is a really good idea. I'll look into it.
