### ISSUE TITLE
Requiring scraper prevents capturing process signals

### ISSUE THREAD

**Issue by enoex** [ruipgil/scraperjs#47]
Not sure if this should be considered a bug or not, but it should be documented somewhere. After scraperjs is required, process.on(SIGNAL, callback) callbacks are never called. This prevents the ability to do things like hooking into process terminations and sending logs somewhere, or doing any sort of post-process termination cleanups.

It is easily reproducable, here are four examples (just run each script and kill the process): https://gist.github.com/enoex/84dca1dae510c671a537

Not sure that there needs to be solved by scraperjs itself, as one solution is to just create a script and run it as a child process from a server, but it's a side effect that should be documented. Thanks!

**Comment by ruipgil** [comment]
This is really interesting, something tells me it may have to do with ``` phantom-node ``` since they do some crazy stuff over there.

I'll investigate.

**Comment by ruipgil** [comment]
This is resolved on ``` phantom v0.8.1 ```.
