### ISSUE TITLE
Feature: Adding the posibility to chose viewport size or any page option when using DynamicScrapper

### ISSUE THREAD

**Issue by maissani** [ruipgil/scraperjs#54]
Hi, 

As you know changing viewport size is important when scrapping directly maps or anything that depends on screen width. 
WIth scrapperjs we can't modify page.viewport options, 
Can you add the possibility to change it by adding a page.viewport or a dinamic merge option into page var on Dynamic Scrapper.

Thanx

**Comment by ruipgil** [comment]
You can pass options to ``` phantomjs ```.

Just pass one extra object as argument and that object will be used as the ``` options ``` object when instantiating the page. Take a look at the [constructor](https://github.com/ruipgil/scraperjs/blob/master/src/DynamicScraper.js#L15) and the [helper method](https://github.com/ruipgil/scraperjs/blob/master/src/DynamicScraper.js#L147).
