### ISSUE TITLE
User-id

### ISSUE THREAD

**Issue by QuentinRoy** [ruipgil/scraperjs#56]
It is sometimes useful to be able to set the user-id/user-agent for the request as the target website may depend on it.

**Comment by ruipgil** [comment]
We use ``` request ```behind the scenes, which allows you to do it very easily.

Check [this post](http://ruipgil.com/2015/12/17/introduction-to-web-scraping.html) out. More specifically, the section *Be a great lad*.

**Comment by QuentinRoy** [comment]
Oh I see. Thank you ruipgil.

As a suggestion, it could be worse documenting it.

Also, it is possible that there is an error in this post. `request`’s `headers` option finishes with an “s”.
